spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/classroom_booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

jwt:
  secret: "super-secret-key-for-dev-only-change-later"
  expiration-ms: 86400000
